@ECHO OFF
SETLOCAL
SET TIMESTAMP=%DATE:~-4%%DATE:~3,2%%DATE:~0,2%-%TIME:~0,2%%TIME:~3,2%
SET NOW_TIME=0%TIME:~1,1%%TIME:~3,2%
ECHO TIMESTAMP = %TIMESTAMP%
ECHO NOW_TIME = %NOW_TIME%

SET UTRO=%TIME:~0,1%
IF "%UTRO%" == " " (
   ECHO Utro yes!
   ECHO UTRO = %UTRO%
   SET TIMESTAMP=%DATE:~-4%%DATE:~3,2%%DATE:~0,2%-0%TIME:~1,1%%TIME:~3,2%
) ELSE (
   ECHO Uzhe day!
   ECHO UTRO = %UTRO%
   SET TIMESTAMP=%DATE:~-4%%DATE:~3,2%%DATE:~0,2%-%TIME:~0,2%%TIME:~3,2%
)
  
ECHO TIMESTAMP = %TIMESTAMP%  